<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="test_errorfail_output" errors="1" failures="1" skipped="0" tests="1" time="0.03" hostname="unknown" timestamp="2024-09-18T18:04:43">
  <properties/>
  <testcase classname="test_errorfail_output" name="test_success" time="0.007">
    <error><![CDATA[Error in tear_down fixture:
Unrecognized function or variable 'unknown_function_call'.
In test_errorfail_output.m at line 13
In tear_down.m at line 21]]></error>
    <failure><![CDATA[Test failed during execution.
In test_errorfail_output.m at line 9]]></failure>
  </testcase>
  <system-out/>
  <system-err/>
</testsuite>
