<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="test_errorfail_output" errors="1" failures="1" tests="1" time="0.0060943" hostname="unknown" timestamp="2015-01-07T21:36:09">
  <properties/>
  <testcase classname="test_errorfail_output" name="test_success">
    <error>
Undefined function or variable 'unknown_function_call'.
In C:\Users\Alexander\repositories\mlunit\sample\failure_samples\test_errorfail_output.m at line 13
In C:\Users\Alexander\repositories\mlunit\src\@function_test_case\tear_down.m at line 21
In C:\Users\Alexander\repositories\mlunit\src\@test_case\run.m at line 66
In C:\Users\Alexander\repositories\mlunit\src\@test_suite\run.m at line 24
In C:\Users\Alexander\repositories\mlunit\src\automation\recursive_test_run.m at line 84
In C:\Users\Alexander\repositories\mlunit\src\automation\recursive_test_run.m at line 41
    </error>
    <failure>
(No failure message provided)
In C:\Users\Alexander\repositories\mlunit\sample\failure_samples\test_errorfail_output.m at line 9.
    </failure>
  </testcase>
  <system-out/>
  <system-err/>
</testsuite>
